theme: jekyll-theme-midnight
title: Draxbot | A Discord Chat Bot
description: Draxbot is a discord chat bot with custom commands to handle server moderation as-well as various World of Warcraft & Overwatch commands.
